import type { Metadata } from "next";
import "./globals.css";
import { Nanum_Brush_Script, Nanum_Pen_Script } from "next/font/google";

const brush = Nanum_Brush_Script({
  weight: "400",
  subsets: ["latin"],
});

const pen = Nanum_Pen_Script({
  weight: "400",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pen.className}>{children}</body>


    </html>
  );
}
